import { defineStore } from 'pinia'
import {
  paint1,
  paint2,
  paint3,
  paint4,
  paint5,
  paint6,
  paint7,
  paint8,
  paint9,
  paint10,
  paint11,
  paint12,
  paint13,
  paint14,
} from '@/assets/images/paints'

export const useProductStore = defineStore('product', {
  state: () => ({
    originalProducts: [
      {
        id: 1,
        image: paint1,
        name: 'Краска Wallquest, Brownsone MS90102-A',
        price: 4725,
        isNew: true,
        inStock: false,
        isContract: true,
        isExclusive: false,
        isSale: true,
        isPopular: false,
        date: '2024-11-18',
      },
      {
        id: 2,
        image: paint2,
        name: 'Краска Wallquest, Brownsone MS90102-B',
        price: 3150,
        isNew: false,
        inStock: true,
        isContract: false,
        isExclusive: true,
        isSale: false,
        isPopular: true,
        date: '2024-10-15',
      },
      {
        id: 3,
        image: paint3,
        name: 'Краска Wallquest, Brownsone MS90102-C',
        price: 5270,
        isNew: true,
        inStock: true,
        isContract: true,
        isExclusive: false,
        isSale: false,
        isPopular: true,
        date: '2024-11-18',
      },
      {
        id: 4,
        image: paint4,
        name: 'Краска Wallquest, Brownsone MS90102-D',
        price: 4990,
        isNew: false,
        inStock: false,
        isContract: true,
        isExclusive: true,
        isSale: true,
        isPopular: false,
        date: '2024-09-20',
      },
      {
        id: 5,
        image: paint5,
        name: 'Краска Wallquest, Brownsone MS90102-E',
        price: 3750,
        isNew: true,
        inStock: true,
        isContract: false,
        isExclusive: false,
        isSale: false,
        isPopular: false,
        date: '2024-11-18',
      },
      {
        id: 6,
        image: paint6,
        name: 'Краска Wallquest, Brownsone MS90102-F',
        price: 4450,
        isNew: true,
        inStock: false,
        isContract: false,
        isExclusive: true,
        isSale: true,
        isPopular: true,
        date: '2024-11-17',
      },
      {
        id: 7,
        image: paint7,
        name: 'Краска Wallquest, Brownsone MS90102-G',
        price: 2890,
        isNew: false,
        inStock: true,
        isContract: true,
        isExclusive: false,
        isSale: false,
        isPopular: false,
        date: '2024-10-10',
      },
      {
        id: 8,
        image: paint8,
        name: 'Краска Wallquest, Brownsone MS90102-H',
        price: 5250,
        isNew: true,
        inStock: true,
        isContract: true,
        isExclusive: true,
        isSale: false,
        isPopular: true,
        date: '2024-11-16',
      },
      {
        id: 9,
        image: paint9,
        name: 'Краска Wallquest, Brownsone MS90102-I',
        price: 4610,
        isNew: false,
        inStock: false,
        isContract: false,
        isExclusive: true,
        isSale: true,
        isPopular: true,
        date: '2024-08-25',
      },
      {
        id: 10,
        image: paint10,
        name: 'Краска Wallquest, Brownsone MS90102-J',
        price: 3990,
        isNew: true,
        inStock: true,
        isContract: false,
        isExclusive: true,
        isSale: false,
        isPopular: false,
        date: '2024-11-18',
      },
      {
        id: 11,
        image: paint11,
        name: 'Краска Wallquest, Brownsone MS90102-K',
        price: 3540,
        isNew: false,
        inStock: true,
        isContract: true,
        isExclusive: false,
        isSale: true,
        isPopular: false,
        date: '2024-09-10',
      },
      {
        id: 12,
        image: paint12,
        name: 'Краска Wallquest, Brownsone MS90102-L',
        price: 4820,
        isNew: true,
        inStock: true,
        isContract: false,
        isExclusive: true,
        isSale: false,
        isPopular: false,
        date: '2024-11-17',
      },
      {
        id: 13,
        image: paint13,
        name: 'Краска Wallquest, Brownsone MS90102-M',
        price: 3200,
        isNew: true,
        inStock: false,
        isContract: true,
        isExclusive: false,
        isSale: true,
        isPopular: false,
        date: '2024-11-15',
      },
      {
        id: 14,
        image: paint14,
        name: 'Краска Wallquest, Brownsone MS90102-N',
        price: 4100,
        isNew: false,
        inStock: false,
        isContract: false,
        isExclusive: true,
        isSale: true,
        isPopular: false,
        date: '2024-08-30',
      },
      {
        id: 15,
        image: paint14,
        name: 'Краска Wallquest, Brownsone MS90102-O',
        price: 4700,
        isNew: false,
        inStock: true,
        isContract: true,
        isExclusive: true,
        isSale: false,
        isPopular: false,
        date: '2024-09-15',
      },
      {
        id: 16,
        image: paint13,
        name: 'Краска Wallquest, Brownsone MS90102-P',
        price: 3750,
        isNew: true,
        inStock: false,
        isContract: true,
        isExclusive: false,
        isSale: true,
        isPopular: false,
        date: '2024-11-18',
      },
      {
        id: 17,
        image: paint12,
        name: 'Краска Wallquest, Brownsone MS90102-Q',
        price: 4600,
        isNew: false,
        inStock: true,
        isContract: false,
        isExclusive: true,
        isSale: false,
        isPopular: false,
        date: '2024-10-01',
      },
      {
        id: 18,
        image: paint11,
        name: 'Краска Wallquest, Brownsone MS90102-R',
        price: 3850,
        isNew: true,
        inStock: false,
        isContract: true,
        isExclusive: true,
        isSale: true,
        isPopular: false,
        date: '2024-11-16',
      },
      {
        id: 19,
        image: paint10,
        name: 'Краска Wallquest, Brownsone MS90102-S',
        price: 3990,
        isNew: false,
        inStock: true,
        isContract: false,
        isExclusive: true,
        isSale: false,
        isPopular: false,
        date: '2024-09-25',
      },
      {
        id: 20,
        image: paint9,
        name: 'Краска Wallquest, Brownsone MS90102-T',
        price: 4690,
        isNew: true,
        inStock: false,
        isContract: true,
        isExclusive: false,
        isSale: true,
        isPopular: false,
        date: '2024-11-18',
      },
      {
        id: 21,
        image: paint8,
        name: 'Краска Wallquest, Brownsone MS90102-U',
        price: 4780,
        isNew: false,
        inStock: true,
        isContract: false,
        isExclusive: true,
        isSale: false,
        isPopular: false,
        date: '2024-09-05',
      },
      {
        id: 22,
        image: paint7,
        name: 'Краска Wallquest, Brownsone MS90102-V',
        price: 3850,
        isNew: true,
        inStock: false,
        isContract: true,
        isExclusive: false,
        isSale: true,
        isPopular: false,
        date: '2024-11-18',
      },
      {
        id: 23,
        image: paint6,
        name: 'Краска Wallquest, Brownsone MS90102-W',
        price: 4590,
        isNew: false,
        inStock: true,
        isContract: false,
        isExclusive: true,
        isSale: true,
        isPopular: false,
        date: '2024-10-10',
      },
      {
        id: 24,
        image: paint5,
        name: 'Краска Wallquest, Brownsone MS90102-X',
        price: 3720,
        isNew: true,
        inStock: true,
        isContract: true,
        isExclusive: false,
        isSale: false,
        isPopular: false,
        date: '2024-11-18',
      },
      {
        id: 25,
        image: paint4,
        name: 'Краска Wallquest, Brownsone MS90102-Y',
        price: 4980,
        isNew: false,
        inStock: false,
        isContract: true,
        isExclusive: true,
        isSale: false,
        isPopular: false,
        date: '2024-09-15',
      },
      {
        id: 26,
        image: paint3,
        name: 'Краска Wallquest, Brownsone MS90102-Z',
        price: 4800,
        isNew: true,
        inStock: true,
        isContract: false,
        isExclusive: false,
        isSale: true,
        isPopular: false,
        date: '2024-11-18',
      },
    ],
    products: [
      {
        id: 1,
        image: paint1,
        name: 'Краска Wallquest, Brownsone MS90102-A',
        price: 4725,
        isNew: true,
        inStock: false,
        isContract: true,
        isExclusive: false,
        isSale: true,
        isPopular: false,
        date: '2024-11-18',
      },
      {
        id: 2,
        image: paint2,
        name: 'Краска Wallquest, Brownsone MS90102-B',
        price: 3150,
        isNew: false,
        inStock: true,
        isContract: false,
        isExclusive: true,
        isSale: false,
        isPopular: true,
        date: '2024-10-15',
      },
      {
        id: 3,
        image: paint3,
        name: 'Краска Wallquest, Brownsone MS90102-C',
        price: 5270,
        isNew: true,
        inStock: true,
        isContract: true,
        isExclusive: false,
        isSale: false,
        isPopular: true,
        date: '2024-11-18',
      },
      {
        id: 4,
        image: paint4,
        name: 'Краска Wallquest, Brownsone MS90102-D',
        price: 4990,
        isNew: false,
        inStock: false,
        isContract: true,
        isExclusive: true,
        isSale: true,
        isPopular: false,
        date: '2024-09-20',
      },
      {
        id: 5,
        image: paint5,
        name: 'Краска Wallquest, Brownsone MS90102-E',
        price: 3750,
        isNew: true,
        inStock: true,
        isContract: false,
        isExclusive: false,
        isSale: false,
        isPopular: false,
        date: '2024-11-18',
      },
      {
        id: 6,
        image: paint6,
        name: 'Краска Wallquest, Brownsone MS90102-F',
        price: 4450,
        isNew: true,
        inStock: false,
        isContract: false,
        isExclusive: true,
        isSale: true,
        isPopular: true,
        date: '2024-11-17',
      },
      {
        id: 7,
        image: paint7,
        name: 'Краска Wallquest, Brownsone MS90102-G',
        price: 2890,
        isNew: false,
        inStock: true,
        isContract: true,
        isExclusive: false,
        isSale: false,
        isPopular: false,
        date: '2024-10-10',
      },
      {
        id: 8,
        image: paint8,
        name: 'Краска Wallquest, Brownsone MS90102-H',
        price: 5250,
        isNew: true,
        inStock: true,
        isContract: true,
        isExclusive: true,
        isSale: false,
        isPopular: true,
        date: '2024-11-16',
      },
      {
        id: 9,
        image: paint9,
        name: 'Краска Wallquest, Brownsone MS90102-I',
        price: 4610,
        isNew: false,
        inStock: false,
        isContract: false,
        isExclusive: true,
        isSale: true,
        isPopular: true,
        date: '2024-08-25',
      },
      {
        id: 10,
        image: paint10,
        name: 'Краска Wallquest, Brownsone MS90102-J',
        price: 3990,
        isNew: true,
        inStock: true,
        isContract: false,
        isExclusive: true,
        isSale: false,
        isPopular: false,
        date: '2024-11-18',
      },
      {
        id: 11,
        image: paint11,
        name: 'Краска Wallquest, Brownsone MS90102-K',
        price: 3540,
        isNew: false,
        inStock: true,
        isContract: true,
        isExclusive: false,
        isSale: true,
        isPopular: false,
        date: '2024-09-10',
      },
      {
        id: 12,
        image: paint12,
        name: 'Краска Wallquest, Brownsone MS90102-L',
        price: 4820,
        isNew: true,
        inStock: true,
        isContract: false,
        isExclusive: true,
        isSale: false,
        isPopular: false,
        date: '2024-11-17',
      },
      {
        id: 13,
        image: paint13,
        name: 'Краска Wallquest, Brownsone MS90102-M',
        price: 3200,
        isNew: true,
        inStock: false,
        isContract: true,
        isExclusive: false,
        isSale: true,
        isPopular: false,
        date: '2024-11-15',
      },
      {
        id: 14,
        image: paint14,
        name: 'Краска Wallquest, Brownsone MS90102-N',
        price: 4100,
        isNew: false,
        inStock: false,
        isContract: false,
        isExclusive: true,
        isSale: true,
        isPopular: false,
        date: '2024-08-30',
      },
      {
        id: 15,
        image: paint14,
        name: 'Краска Wallquest, Brownsone MS90102-O',
        price: 4700,
        isNew: false,
        inStock: true,
        isContract: true,
        isExclusive: true,
        isSale: false,
        isPopular: false,
        date: '2024-09-15',
      },
      {
        id: 16,
        image: paint13,
        name: 'Краска Wallquest, Brownsone MS90102-P',
        price: 3750,
        isNew: true,
        inStock: false,
        isContract: true,
        isExclusive: false,
        isSale: true,
        isPopular: false,
        date: '2024-11-18',
      },
      {
        id: 17,
        image: paint12,
        name: 'Краска Wallquest, Brownsone MS90102-Q',
        price: 4600,
        isNew: false,
        inStock: true,
        isContract: false,
        isExclusive: true,
        isSale: false,
        isPopular: false,
        date: '2024-10-01',
      },
      {
        id: 18,
        image: paint11,
        name: 'Краска Wallquest, Brownsone MS90102-R',
        price: 3850,
        isNew: true,
        inStock: false,
        isContract: true,
        isExclusive: true,
        isSale: true,
        isPopular: false,
        date: '2024-11-16',
      },
      {
        id: 19,
        image: paint10,
        name: 'Краска Wallquest, Brownsone MS90102-S',
        price: 3990,
        isNew: false,
        inStock: true,
        isContract: false,
        isExclusive: true,
        isSale: false,
        isPopular: false,
        date: '2024-09-25',
      },
      {
        id: 20,
        image: paint9,
        name: 'Краска Wallquest, Brownsone MS90102-T',
        price: 4690,
        isNew: true,
        inStock: false,
        isContract: true,
        isExclusive: false,
        isSale: true,
        isPopular: false,
        date: '2024-11-18',
      },
      {
        id: 21,
        image: paint8,
        name: 'Краска Wallquest, Brownsone MS90102-U',
        price: 4780,
        isNew: false,
        inStock: true,
        isContract: false,
        isExclusive: true,
        isSale: false,
        isPopular: false,
        date: '2024-09-05',
      },
      {
        id: 22,
        image: paint7,
        name: 'Краска Wallquest, Brownsone MS90102-V',
        price: 3850,
        isNew: true,
        inStock: false,
        isContract: true,
        isExclusive: false,
        isSale: true,
        isPopular: false,
        date: '2024-11-18',
      },
      {
        id: 23,
        image: paint6,
        name: 'Краска Wallquest, Brownsone MS90102-W',
        price: 4590,
        isNew: false,
        inStock: true,
        isContract: false,
        isExclusive: true,
        isSale: true,
        isPopular: false,
        date: '2024-10-10',
      },
      {
        id: 24,
        image: paint5,
        name: 'Краска Wallquest, Brownsone MS90102-X',
        price: 3720,
        isNew: true,
        inStock: true,
        isContract: true,
        isExclusive: false,
        isSale: false,
        isPopular: false,
        date: '2024-11-18',
      },
      {
        id: 25,
        image: paint4,
        name: 'Краска Wallquest, Brownsone MS90102-Y',
        price: 4980,
        isNew: false,
        inStock: false,
        isContract: true,
        isExclusive: true,
        isSale: false,
        isPopular: false,
        date: '2024-09-15',
      },
      {
        id: 26,
        image: paint3,
        name: 'Краска Wallquest, Brownsone MS90102-Z',
        price: 4800,
        isNew: true,
        inStock: true,
        isContract: false,
        isExclusive: false,
        isSale: true,
        isPopular: false,
        date: '2024-11-18',
      },
    ],
    filters: {
      isNew: false,
      inStock: false,
      isContract: false,
      isExclusive: false,
      isSale: false,
    },
  }),
  actions: {
    sortExpensiveFirst() {
      this.products.sort((a, b) => b.price - a.price)
    },
    sortCheapFirst() {
      this.products.sort((a, b) => a.price - b.price)
    },
    sortNewFirst() {
      this.products.sort((a, b) => new Date(b.date) - new Date(a.date))
    },
    sortPopularFirst() {
      this.products.sort((a, b) => b.isPopular - a.isPopular)
    },
    filterNew() {
      this.filters.isNew = !this.filters.isNew
      this.applyFilters()
    },
    filterInStock() {
      this.filters.inStock = !this.filters.inStock
      this.applyFilters()
    },
    filterContract() {
      this.filters.isContract = !this.filters.isContract
      this.applyFilters()
    },
    filterExclusive() {
      this.filters.isExclusive = !this.filters.isExclusive
      this.applyFilters()
    },
    filterSale() {
      this.filters.isSale = !this.filters.isSale
      this.applyFilters()
    },

    applyFilters() {
      let filteredProducts = [...this.originalProducts]

      if (this.filters.isNew) {
        filteredProducts = filteredProducts.filter((product) => product.isNew === true)
      }

      if (this.filters.inStock) {
        filteredProducts = filteredProducts.filter((product) => product.inStock === true)
      }

      if (this.filters.isContract) {
        filteredProducts = filteredProducts.filter((product) => product.isContract === true)
      }

      if (this.filters.isExclusive) {
        filteredProducts = filteredProducts.filter((product) => product.isExclusive === true)
      }

      if (this.filters.isSale) {
        filteredProducts = filteredProducts.filter((product) => product.isSale === true)
      }

      this.products = filteredProducts
    },
  },
})
